#!/bin/sh

# Uses rofi -dmenu to list out all folders in your music folder. Enter makes strawberry play all music files from the selected folder.

# CURRENT_FOLDER_LOCATION is used for persitance
# MUSIC_FOLDER should be changed to your music folder
# ROFI_THEME should be changed to your rofi theme

CURRENT_FOLDER_LOCATION="$XDG_CACHE_HOME/strawberry/current-folder"
CURRENT_FOLDER=$(cat "$CURRENT_FOLDER_LOCATION")
MUSIC_FOLDER="/mnt/seagate-e/music/"
ROFI_THEME="${HOME}/.config/rofi/launchers/type-4/style-music.rasi"

PLAY_FOLDER=$(find "$MUSIC_FOLDER" -mindepth 1 -type d | sed "s#$MUSIC_FOLDER##" | sort | rofi -dmenu -i -no-custom -window-title "♫" -select ${CURRENT_FOLDER} -sorting-method fzf -theme $ROFI_THEME)

[[ -n "$PLAY_FOLDER" ]] || exit 1

ROFI_CHOICE="$(echo -e 'Replace\nAppend' | rofi -dmenu  -theme $ROFI_THEME -theme-str 'window {width: 300px; height: 70px; }  inputbar{enabled:false;}')"

[[ -n "$ROFI_CHOICE" ]] || exit 1

if [[ "$ROFI_CHOICE" == "Replace" ]];then
	strawberry --play temp --load "$MUSIC_FOLDER$PLAY_FOLDER"
	echo "$PLAY_FOLDER" > "$XDG_CACHE_HOME/strawberry/current-folder"
	exit 0
elif [[ "$ROFI_CHOICE" == "Append" ]]
	strawberry --append "$MUSIC_FOLDER$PLAY_FOLDER"
	echo "$PLAY_FOLDER" > "$XDG_CACHE_HOME/strawberry/current-folder"
	exit 0
fi

#strawberry --play temp --load "$MUSIC_FOLDER$PLAY_FOLDER"
#echo "$PLAY_FOLDER" > "$CURRENT_FOLDER_LOCATION"
